{
  "openapi": "3.0.0",
  "info": {
    "title": "Atlas",
    "description": "Essa é uma descrição sobre o Atlas API",
    "version": "1.0.0"
  },
  "tags": [
    {
      "name": "users",
      "description": "Gerenciamento de usuários"
    }
  ],
  "paths": {
    "/users": {
      "post": {
        "summary": "Cria um novo usuário.",
        "description": "Cria um novo usuário",
        "required": true,
        "tags": ["users"],
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "in": "body",
            "name": "body",
            "description": "Campos obrigatórios para criação de um usuário.",
            "required": true,
            "schema": {
              "properties": {
                "name": {
                  "type": "string"
                },
                "email": {
                  "type": "string"
                }
              },
              "example": {
                "name": "John Doe",
                "email": "john@doe.example"
              }
            }
          }
        ],
        "responses": {
          "201": {
            "description": "Operação realizada com sucesso",
            "content": {
              "apllication/json": {
                "schema": {
                  "$ref": "#/components/schemas/User"
                },
                "example": {
                  "admin": false,
                  "name": "John Doe",
                  "email": "john@doe.example",
                  "created_at": "2021-12-08T18:00:00.992Z",
                  "updated_at": "2021-12-08T18:00:00.992Z"
                }
              }
            }
          },

          "400": {
            "description": "Email já esta sendo utilizado",
            "content": {
              "apllication/json": {
                "schema": {
                  "type": "object",
                  "example": {
                    "error": "This email alredy exists."
                  }
                }
              }
            }
          }
        }
      },
      "get": {
        "summary": "Retorna todos os usuários",
        "description": "Somente usuário admin pode acessar",
        "tags": ["users"],
        "parameters": [
          {
            "name": "user_id",
            "in": "header",
            "description": "ID do usuário (uuid)",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Operação realizada com sucesso",
            "content": {
              "apllication/json": {
                "schema": {
                  "$ref": "#/components/schemas/User"
                },
                "example":
                [
                  {
                  "admin": false,
                  "name": "John Doe",
                  "email": "john@doe.example",
                  "created_at": "2021-12-08T18:00:00.992Z",
                  "updated_at": "2021-12-08T18:00:00.992Z"
                  },
                  {
                    "admin": false,
                    "name": "John Doe",
                    "email": "john@doe.example",
                    "created_at": "2021-12-08T18:00:00.992Z",
                    "updated_at": "2021-12-08T18:00:00.992Z"
                  }
                ]
              }
            }
          },
          "404": {
            "description": "Usuário não encontrado",
            "content": {
              "apllication/json": {
                "schema": {
                  "type": "object",
                  "example": {
                    "error": "You need to be an administrator to list all users."
                  }
                }
              }
            }
          }
        }
      }
    },
    "/users/{user_id}": {
      "get": {
        "summary": "Retorna um usuário específico",
        "tags": ["users"],
        "parameters": [
          {
            "name": "user_id",
            "in": "path",
            "description": "ID do usuário (uuid)",
            "required": true
          }
        ],
        "responses": {
          "201": {
            "description": "Operação realizada com sucesso",
            "content": {
              "apllication/json": {
                "schema": {
                  "$ref": "#/components/schemas/User"
                },
                "example": {
                  "admin": false,
                  "name": "John Doe",
                  "email": "john@doe.example",
                  "created_at": "2021-12-08T18:00:00.992Z",
                  "updated_at": "2021-12-08T18:00:00.992Z"
                }
              }
            }
          },

          "400": {
            "description": "Usuário não encontrado.",
            "content": {
              "apllication/json": {
                "schema": {
                  "type": "object",
                  "example": {
                    "error": "User not found."
                  }
                }
              }
            }
          }
        }
      }
    },
    "/users/{user_id}/admin": {
      "patch": {
        "summary": "Torna um admin um usuário",
        "description": "Torna um admin um usuário",
        "tags": ["users"],
        "parameters": [
          {
            "name": "user_id",
            "in": "path",
            "description": "ID do usuário (uuid)",
            "required": true
          }
        ],
        "responses": {
          "201": {
            "description": "Operação realizada com sucesso",
            "content": {
              "apllication/json": {
                "schema": {
                  "$ref": "#/components/schemas/User"
                },
                "example": {
                  "admin": true,
                  "name": "John Doe",
                  "email": "john@doe.example",
                  "created_at": "2021-12-08T18:00:00.992Z",
                  "updated_at": "2021-12-08T18:00:00.992Z"
                }
              }
            }
          },

          "400": {
            "description": "Usuário não encontrado.",
            "content": {
              "apllication/json": {
                "schema": {
                  "type": "object",
                  "example": {
                    "error": "User not found."
                  }
                }
              }
            }
          }
        }
      }
    }
  },
  "components": {
    "schemas": {
      "User": {
        "type": "object",
        "properties": {
          "admin": {
            "type": "boolean"
          },
          "id": {
            "type": "string"
          },
          "name": {
            "type": "string"
          },
          "email": {
            "type": "string"
          },
          "created_at": {
            "type": "string"
          },
          "updated_at": {
            "type": "string"
          }
        }
      }
    }
  }
}
